"""Add temp_files table

Revision ID: 6d23cc74d14b
Revises: ef0d9f619804
Create Date: 2025-09-05 15:33:27.064900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d23cc74d14b'
down_revision: Union[str, Sequence[str], None] = 'ef0d9f619804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('statement_format', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('processed_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_statements')
    # ### end Alembic commands ###
