"""Add temp_files table

Revision ID: ef0d9f619804
Revises: 4ffb626d9737
Create Date: 2025-09-05 15:30:08.688865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0d9f619804'
down_revision: Union[str, Sequence[str], None] = '4ffb626d9737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('upload_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_files')
    # ### end Alembic commands ###
